import NavBar from "../components/navBar";
import "./globals.css";
import { TaskProvider } from "@/context/TasksContext";
import {Toaster} from "./Toaster"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TaskProvider>
          <NavBar />
          {children}
          <Toaster
          position="bottom-left"
          reverseOrder={false}/>
        </TaskProvider>
      </body>
    </html>
  );
}
